// <auto-generated />
using System;
using ITDeveloper.Data.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITDeveloper.Data.Migrations
{
    [DbContext(typeof(ITDeveloperDbContext))]
    [Migration("20200418233719_UpdateModeCreating")]
    partial class UpdateModeCreating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.Mural", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notification")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tittle")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Murals");
                });

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("Cpf")
                        .HasColumnType("varchar(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("EmissionDate");

                    b.Property<DateTime>("HospitalizationDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Rg")
                        .HasColumnName("RG")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("RgEmitterOrgan")
                        .HasColumnName("RgEmitterOrgan")
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("StateId");

                    b.Property<int>("type");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("TBL_PATIENT");
                });

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.PatientState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("TBL_PATIENT_STATE");
                });

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.Patient", b =>
                {
                    b.HasOne("ITDeveloper.Domain.Entitites.PatientState", "State")
                        .WithMany("Patients")
                        .HasForeignKey("StateId");
                });
#pragma warning restore 612, 618
        }
    }
}
