// <auto-generated />
using System;
using ITDeveloper.Data.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITDeveloper.Data.Migrations
{
    [DbContext(typeof(ITDeveloperDbContext))]
    [Migration("20200417205746_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.Mural", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Email");

                    b.Property<string>("Notification");

                    b.Property<string>("Tittle");

                    b.HasKey("Id");

                    b.ToTable("Murals");
                });

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Cpf");

                    b.Property<string>("Email");

                    b.Property<DateTime>("EmissionDate");

                    b.Property<DateTime>("HospitalizationDate");

                    b.Property<string>("Name");

                    b.Property<string>("RG");

                    b.Property<string>("RGEmitterOrgan");

                    b.Property<Guid?>("stateId");

                    b.Property<int>("type");

                    b.HasKey("Id");

                    b.HasIndex("stateId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.PatientState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PatientStates");
                });

            modelBuilder.Entity("ITDeveloper.Domain.Entitites.Patient", b =>
                {
                    b.HasOne("ITDeveloper.Domain.Entitites.PatientState", "state")
                        .WithMany()
                        .HasForeignKey("stateId");
                });
#pragma warning restore 612, 618
        }
    }
}
